# The Site Configuration

# Import the theme
theme: jekyll-theme-minimal

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: "/Dokumantasyon"